version: 2.1
jobs:
   build:
        machine: 
          image: ubuntu-2004:202111-01
        steps:
          - checkout 

          #build image
          - run: |         
              docker info
              docker build -t quest-api . -f ./src/Quest.Api/Dockerfile

          # deploy the image
          - run: |         
              docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
              docker tag quest-api registry.heroku.com/$HEROKU_APP_NAME/web
              docker push registry.heroku.com/$HEROKU_APP_NAME/web                
              curl https://cli-assets.heroku.com/install.sh | sh
              heroku container:release web -a $HEROKU_APP_NAME
workflows:
  version: 2
  build-deploy:
        jobs:
          - build:
              filters:
                branches:
                   only:
                     - master
                     - /release*/